# Model arguments
model_name_or_path: Qwen/Qwen2.5-3B
model_revision: main
torch_dtype: bfloat16

# Data training arguments
# dataset_name: AI-MO/NuminaMath-TIR
# dataset_configs:
# - all

dataset_name: Jiayi-Pan/Countdown-Tasks-3to4
dataset_configs:
- train
# Num processes is less by 1 as vLLM is using 1 GPU
num_processes: 1

# GRPO trainer config
bf16: true
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.8
temperature: 1.0
do_eval: true
eval_strategy: steps
eval_steps: 100
save_strategy: steps
save_steps: 100
save_total_limit: 3

# maybe this will change
greater_is_better: False
metric_for_best_model: 

# KL coef
beta: 0.001

gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
reward_funcs:
- accuracy

# hub_model_id: Qwen2.5-1.5B-Open-R1-GRPO
# hub_strategy: every_save
learning_rate: 1.0e-06
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: constant
warmup_ratio: 0
max_prompt_length: 256
max_completion_length: 1024
num_generations: 5
max_steps: -1
num_train_epochs: 1
output_dir: data/countdown
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
push_to_hub: false
# report_to:
# #- wandb
# - console
seed: 42
